### ISSUE TITLE
cloudwatch-loki-shipper lambda function kills before it starts

### ISSUE THREAD

**Issue by aishvaryaps** [ClaudioWaldvogel/cloudwatch-loki-shipper#1]
I run following command:

python demo/cli.py shipper -l http://abdef4035ea5611e9897f0a855af7b5e-851135046.eu-west-3.elb.amazonaws.com:80 start

Starting lambda: loki-shipper
Traceback (most recent call last):
  File "demo/cli.py", line 296, in <module>
    cli()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "demo/cli.py", line 118, in shipper
    __start_lambda(config) if action == 'start' else __stop_lambda(config)
  File "demo/cli.py", line 274, in __start_lambda
    raise Exception('Failed to update Lambda function', e)
Exception: ('Failed to update Lambda function', MemoryError())

where am I going wrong?

Can I know how do I configure this lambda function from AWS Console? I am new to AWS CLI

**Comment by aishvaryaps** [comment]
This worked fine now.
Loki-shipper lambda function is running
I tried the demo mentioned in Github repo
2 lambda functions were created with log subscription
but I cant see my logs in grafana loki..
Is it necessary that Grafana has to be deployed in the same region?

I use a loadbalancer running on loki service

**Comment by kush2100** [comment]
I have configure in Lambda and try to push cloudwatch log group in Grafana Loki, but i couldn't find any log on Loki. Can you please help on this matter.
I try to run query but log not found : {driver="Python",location=""us-west-2",name=~"loki.*"} Confi
How to check log push on loki ?
