### ISSUE TITLE
I am getting error while creating log-subscription as below; could you check this.

### ISSUE THREAD

**Issue by Baludocker** [ClaudioWaldvogel/cloudwatch-loki-shipper#2]
[ec2-user@ip-172-30-209-119 cloudwatch-loki-shipper]$ python demo/cli.py -p default -r us-east-1  attach /aws/lambda/DevOpsShutdown
Created/Updated LogGroup: /aws/lambda/DevOpsShutdown
Traceback (most recent call last):
  File "demo/cli.py", line 297, in <module>
    cli()
  File "/home/ec2-user/cloudwatch-loki-shipper/venv/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/ec2-user/cloudwatch-loki-shipper/venv/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/ec2-user/cloudwatch-loki-shipper/venv/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ec2-user/cloudwatch-loki-shipper/venv/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ec2-user/cloudwatch-loki-shipper/venv/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "demo/cli.py", line 128, in attach
    __create_log_subscription(group)
  File "demo/cli.py", line 170, in __create_log_subscription
    raise Exception('Failed to create log subscription. Is loki-shipper lambda running?', e)
Exception: ('Failed to create log subscription. Is loki-shipper lambda running?', LimitExceededException(u'An error occurred (LimitExceededException) when calling the PutSubscriptionFilter operation: Resource limit exceeded.',))
(venv) [ec2-user@ip-172-30-209-119 cloudwatch-loki-shipper]$ aws lo

**Comment by ancellink** [comment]
I also facing the same issue.
An error occurred (InvalidParameterException) when calling the PutSubscriptionFilter operation: Could not execute the lambda function. Make sure you have given CloudWatch Logs permission to execute your function.
